yaw_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.1
    kD: 0.0
    bias: 0.0
pitch_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.1
    kD: 0.0
    bias: 0.0
roll_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.1
    kD: 0.0
    bias: 0.0
surge_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 40.0
    kD: 0.0
    bias: 0.0
sway_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 50.0
    kD: 0.0
    bias: 0.0
heave_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 50.0
    kD: 0.0
    bias: 0.0
x_translation_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 1.0
    kD: 0.0
    bias: 0.0
    max: 1.5
y_translation_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 1.0
    kD: 0.0
    bias: 0.0
    max: 1.5
z_translation_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 1.0
    kD: 0.0
    bias: 0.0
    max: 0.5
