yaw_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 4.0
    kD: 0.0
    bias: 0.378
pitch_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.0
    kD: 0.0
    bias: 0.0
roll_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.5
    kD: 0.0
    bias: 0.0
surge_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 85.0
    kD: 0.0
    bias: 0.0
sway_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 115.0
    kD: 0.0
    bias: 0.0
heave_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 80.0
    kD: 0.0
    bias: -18.5
x_translation_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.0
    kD: 0.0
    bias: 0.0
    max: 1.5
y_translation_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.0
    kD: 0.0
    bias: 0.0
    max: 1.5
z_translation_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.0
    kD: 0.0
    bias: 0.0
    max: 1.5






