name: Generate Docs
on: [push]

jobs:
    generate_docs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Generate Docs
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - run: python3 generatedocs.py

        - name: Deploy Docs
          uses: peaceiris/actions-gh-pages@v3
          with:
            personal_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
            publish_branch: gh-pages
          

            